### ISSUE TITLE
Pozdrav Stefane!

### ISSUE THREAD

**Issue by DjordjeNedovic** [JerSefJeTu/PoslovnaBanka#2]
Stefane,
CRUD i view forme za RACUN, GASENJE RACUNA i  BANKU.

**Comment by stek93** [comment]
Umjesto View forme za Racun, napravljena je metoda za generisanje racuna. 
Gasenje racuna nema View formu, i bice naknadno odradjena metoda koja se kaci na bazu i kreira gasenje racuna.
Nema smisla da se pravi crud za banku, u slucaju da nema admin side-a.
